In [1]:
# Import Dependencies

import pandas as pd
import numpy as np

In [2]:
# load and read csv file into DataFrame

merged_file_to_load = "../Resources/NFL_Merged_df.csv"
NFL_Merged_df = pd.read_csv(merged_file_to_load)
NFL_Merged_df

,Player,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap_Hit,Salary%,...,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won_Superbowl
0,Mark Sanchez,25,2011,QB,Offense,NYJ,14225000,0,17228125,0.134,...,0,0.500000,2,377,363,14,0.398438,0.500000,No,No
1,Dwight Freeney,31,2011,OLB,Defense,IND,11420000,2500000,16420000,0.134,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
2,Larry Fitzgerald,28,2011,WR,Offense,ARI,2000000,5000000,16250000,0.133,...,0,0.500000,2,312,348,-36,0.390625,0.468750,No,No
3,Mario Williams,26,2011,DE,Defense,HOU,13800000,0,16200000,0.135,...,0,0.625000,1,381,278,103,0.412500,0.453125,Yes,No
4,Peyton Manning,35,2011,QB,Offense,IND,3400000,4000000,16000000,0.130,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21996,Stephen Sullivan,25,2021,WR,Offense,CAR,36666,0,36666,0.000,...,0,0.294118,4,304,404,-100,0.411765,0.508651,No,No
21997,Jalen Camp,23,2021,WR,Offense,HOU,36666,0,36666,0.000,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21998,Michael Dwumfour,23,2021,DT,Defense,HOU,36666,0,36666,0.000,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21999,Tarik Black,23,2021,WR,Offense,NYJ,36666,0,36666,0.000,...,0,0.235294,4,310,504,-194,0.426471,0.512111,No,No
22000,Connor Strachan,26,2021,LB,Defense,HOU,36666,0,36666,0.000,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No

In [3]:
# Drop Player in preperation for machine learning

NFL_Merged_df = NFL_Merged_df.drop(columns=["Player"])
NFL_Merged_df

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
0,25,2011,QB,Offense,NYJ,14225000,0,17228125,0.134,AFC,...,0,0.500000,2,377,363,14,0.398438,0.500000,No,No
1,31,2011,OLB,Defense,IND,11420000,2500000,16420000,0.134,AFC,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
2,28,2011,WR,Offense,ARI,2000000,5000000,16250000,0.133,NFC,...,0,0.500000,2,312,348,-36,0.390625,0.468750,No,No
3,26,2011,DE,Defense,HOU,13800000,0,16200000,0.135,AFC,...,0,0.625000,1,381,278,103,0.412500,0.453125,Yes,No
4,35,2011,QB,Offense,IND,3400000,4000000,16000000,0.130,AFC,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21996,25,2021,WR,Offense,CAR,36666,0,36666,0.000,NFC,...,0,0.294118,4,304,404,-100,0.411765,0.508651,No,No
21997,23,2021,WR,Offense,HOU,36666,0,36666,0.000,AFC,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21998,23,2021,DT,Defense,HOU,36666,0,36666,0.000,AFC,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21999,23,2021,WR,Offense,NYJ,36666,0,36666,0.000,AFC,...,0,0.235294,4,310,504,-194,0.426471,0.512111,No,No
22000,26,2021,LB,Defense,HOU,36666,0,36666,0.000,AFC,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No

In [4]:
# Verify years in Dataset

NFL_Merged_df.Year.unique()

array([2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021],
      dtype=int64)

## Create 11 seperate Dataframes for each year

In [5]:
# Create dataframe for 2011 only

value = [2011]
df2011 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2011

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
0,25,2011,QB,Offense,NYJ,14225000,0,17228125,0.134,AFC,...,0,0.5000,2,377,363,14,0.398438,0.500000,No,No
1,31,2011,OLB,Defense,IND,11420000,2500000,16420000,0.134,AFC,...,0,0.1250,4,243,430,-187,0.593750,0.539062,No,No
2,28,2011,WR,Offense,ARI,2000000,5000000,16250000,0.133,NFC,...,0,0.5000,2,312,348,-36,0.390625,0.468750,No,No
3,26,2011,DE,Defense,HOU,13800000,0,16200000,0.135,AFC,...,0,0.6250,1,381,278,103,0.412500,0.453125,Yes,No
4,35,2011,QB,Offense,IND,3400000,4000000,16000000,0.130,AFC,...,0,0.1250,4,243,430,-187,0.593750,0.539062,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615,23,2011,QB,Offense,MIA,44117,0,44117,0.000,AFC,...,0,0.3750,3,329,313,16,0.416667,0.503906,No,No
1616,22,2011,WR,Offense,CIN,44117,0,44117,0.000,AFC,...,0,0.5625,3,344,323,21,0.326389,0.492188,Yes,No
1617,25,2011,OLB,Defense,NYJ,22059,0,22059,0.000,AFC,...,0,0.5000,2,377,363,14,0.398438,0.500000,No,No
1618,21,2011,RB,Offense,MIN,22058,0,22058,0.000,NFC,...,0,0.1875,4,340,449,-109,0.395833,0.558594,No,No
1619,23,2011,T,Offense,LAR/STL,0,1666,1666,0.000,NFC,...,0,0.1250,4,193,407,-214,0.531250,0.589844,No,No

In [6]:
# Create dataframe for 2012 only

# values = [2011, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]
# df2012 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(values)==False])

# df2012 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df["Year"] == "2012"])

# df2012 = NFL_Merged_df[NFL_Merged_df["Year"] == "2012"]

# df2012 = NFL_Merged_df[NFL_Merged_df["Year"]=="2012"]

# df2012 = pd.DataFrame(NFL_Merged_df.loc[NFL_Merged_df["Year"]=="2012"])

value = [2012] 
df2012 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])


df2012

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
1620,32,2012,OLB,Defense,IND,14035000,2500000,19035000,0.158,AFC,...,0,0.68750,2,357,387,-30,0.403409,0.441406,Yes,No
1621,27,2012,DE,Defense,LAR/STL,10310000,0,19007500,0.158,NFC,...,1,0.46875,3,299,348,-49,0.491071,0.535156,No,No
1622,36,2012,QB,Offense,DEN,18000000,0,18000000,0.149,AFC,...,0,0.81250,1,481,289,192,0.384615,0.457031,Yes,No
1623,27,2012,ILB,Defense,SF,1904000,13113332,17777332,0.147,NFC,...,1,0.71875,1,397,273,124,0.477273,0.500000,Yes,No
1624,28,2012,OLB,Defense,DEN,14000000,500000,15623000,0.130,AFC,...,0,0.81250,1,481,289,192,0.384615,0.457031,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3427,23,2012,S,Defense,ARI,45882,0,45882,0.000,NFC,...,0,0.31250,4,250,357,-107,0.475000,0.550781,No,No
3428,24,2012,FS,Defense,HOU,390000,0,22942,0.000,AFC,...,0,0.75000,1,416,331,85,0.432292,0.496094,Yes,No
3429,25,2012,TE,Offense,JAX,22941,0,22941,0.000,AFC,...,0,0.12500,4,255,444,-189,0.531250,0.539062,No,No
3430,24,2012,T,Offense,LAR/STL,0,3334,3334,0.000,NFC,...,1,0.46875,3,299,348,-49,0.491071,0.535156,No,No
3431,24,2012,RT,Offense,MIA,1500,0,1500,0.000,AFC,...,0,0.43750,2,288,317,-29,0.410714,0.496094,No,No

In [7]:
# Create dataframe for 2013 only

value = [2013]
df2013 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2013

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
3432,32,2013,QB,Offense,NYG,13000000,2600000,20850000,0.167,NFC,...,0,0.43750,3,294,383,-89,0.366071,0.519531,No,No
3433,25,2013,QB,Offense,DET,4000000,5500000,17820000,0.145,NFC,...,0,0.43750,3,395,376,19,0.401786,0.457031,No,No
3434,37,2013,QB,Offense,DEN,15000000,0,17500000,0.124,AFC,...,0,0.81250,1,606,399,207,0.423077,0.468750,Yes,No
3435,34,2013,QB,Offense,NO,9750000,7400000,17400000,0.138,NFC,...,0,0.68750,2,414,304,110,0.454545,0.515625,Yes,No
3436,31,2013,DE,Defense,MIN,14280612,2583344,17063956,0.130,NFC,...,1,0.34375,4,391,480,-89,0.450000,0.511719,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5296,23,2013,RB,Offense,HOU,405000,0,23823,0.000,AFC,...,0,0.12500,4,276,428,-152,0.500000,0.558594,No,No
5297,23,2013,DE,Defense,HOU,405000,0,23823,0.000,AFC,...,0,0.12500,4,276,428,-152,0.500000,0.558594,No,No
5298,22,2013,CB,Defense,IND,405000,0,23823,0.000,AFC,...,0,0.68750,1,391,336,55,0.448864,0.484375,Yes,No
5299,23,2013,S,Defense,NE,405000,0,23823,0.000,AFC,...,0,0.75000,1,444,338,106,0.427083,0.472656,Yes,No
5300,23,2013,CB,Defense,GB,405000,0,23823,0.000,NFC,...,1,0.53125,1,417,428,-11,0.371094,0.453125,Yes,No

In [8]:
# Create dataframe for 2014 only

value = [2014]
df2014 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2014

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
5301,27,2014,DT,Defense,DET,12550000,0,22412500,0.170,NFC,...,0,0.6875,2,321,282,39,0.392045,0.468750,Yes,No
5302,26,2014,DT,Defense,TB,17500000,1100000,21295000,0.153,NFC,...,0,0.1250,4,277,410,-133,0.468750,0.480469,No,No
5303,33,2014,QB,Offense,NYG,15150000,0,20400000,0.155,NFC,...,0,0.3750,3,380,400,-20,0.322917,0.511719,No,No
5304,32,2014,QB,Offense,PIT,12100000,0,18895000,0.141,AFC,...,0,0.6875,1,436,368,68,0.477273,0.445312,Yes,No
5305,29,2014,DE,Defense,BUF,1900000,3800000,18800000,0.125,AFC,...,0,0.5625,2,343,289,54,0.486111,0.515625,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7289,23,2014,RB,Offense,ATL,420000,0,24705,0.000,NFC,...,0,0.3750,3,381,417,-36,0.375000,0.476562,No,No
7290,24,2014,LS,Special Teams,CLE,420000,0,24705,0.000,AFC,...,0,0.4375,4,299,337,-38,0.366071,0.472656,No,No
7291,23,2014,QB,Offense,CLE,420000,0,24705,0.000,AFC,...,0,0.4375,4,299,337,-38,0.366071,0.472656,No,No
7292,23,2014,RB,Offense,MIN,420000,0,24705,0.000,NFC,...,0,0.4375,3,325,343,-18,0.303571,0.472656,No,No
7293,24,2014,DT,Defense,DAL,0,1666,1666,0.000,NFC,...,0,0.7500,1,467,352,115,0.421875,0.445312,Yes,No

In [9]:
# Create dataframe for 2015 only

value = [2015]
df2015 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2015

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
7294,36,2015,QB,Offense,NO,13550000,7400000,23800000,0.164,NFC,...,0,0.4375,3,408,476,-68,0.401786,0.503906,No,No
7295,34,2015,QB,Offense,LAC/SD,15000000,4500000,21166668,0.148,AFC,...,0,0.2500,4,320,398,-78,0.328125,0.527344,No,No
7296,30,2015,WR,Offense,DET,12500000,3200000,20558000,0.142,NFC,...,0,0.4375,3,358,400,-42,0.428571,0.535156,No,No
7297,29,2015,DE,Defense,CAR,9750000,6000000,20020000,0.134,NFC,...,0,0.9375,1,500,308,192,0.437500,0.441406,Yes,No
7298,30,2015,QB,Offense,ATL,11500000,5600000,19500000,0.133,NFC,...,0,0.5000,2,339,345,-6,0.453125,0.480469,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9366,25,2015,DE,Defense,NO,25588,0,25588,0.000,NFC,...,0,0.4375,3,408,476,-68,0.401786,0.503906,No,No
9367,22,2015,RB,Offense,LAR/STL,25588,0,25588,0.000,NFC,...,0,0.4375,3,280,330,-50,0.482143,0.527344,No,No
9368,24,2015,CB,Defense,LAR/STL,25588,0,25588,0.000,NFC,...,0,0.4375,3,280,330,-50,0.482143,0.527344,No,No
9369,24,2015,TE,Offense,ATL,25588,0,25588,0.000,NFC,...,0,0.5000,2,339,345,-6,0.453125,0.480469,No,No
9370,23,2015,DT,Defense,JAX,25588,0,25588,0.000,AFC,...,0,0.3125,3,376,448,-72,0.375000,0.472656,No,No

In [10]:
# Create dataframe for 2016 only

value = [2016]
df2016 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2016

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
9371,35,2016,QB,Offense,NYG,17500000,6200000,24200000,0.145,NFC,...,0,0.68750,2,310,284,26,0.454545,0.486328,Yes,No
9372,34,2016,QB,Offense,PIT,17750000,6200000,23950000,0.152,AFC,...,0,0.68750,1,399,327,72,0.423295,0.494141,Yes,No
9373,31,2016,QB,Offense,ATL,15750000,5600000,23750000,0.150,NFC,...,0,0.68750,1,540,406,134,0.451705,0.480469,Yes,No
9374,31,2016,QB,Offense,BAL,4000000,13800000,22550000,0.145,AFC,...,0,0.50000,2,343,321,22,0.363281,0.498047,No,No
9375,28,2016,QB,Offense,DET,17000000,5500000,22500000,0.143,NFC,...,0,0.56250,2,346,358,-12,0.392361,0.474609,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11464,24,2016,S,Defense,NO,26470,0,26470,0.000,NFC,...,0,0.43750,3,469,454,15,0.392857,0.523438,No,No
11465,23,2016,RB,Offense,NYJ,26470,0,26470,0.000,AFC,...,0,0.31250,4,275,409,-134,0.312500,0.517578,No,No
11466,23,2016,CB,Defense,NYJ,26470,0,26470,0.000,AFC,...,0,0.31250,4,275,409,-134,0.312500,0.517578,No,No
11467,26,2016,OLB,Defense,LAC/SD,26470,0,26470,0.000,AFC,...,0,0.31250,4,410,423,-13,0.512500,0.542969,No,No
11468,24,2016,WR,Offense,SEA,26470,0,26470,0.000,NFC,...,1,0.65625,1,354,292,62,0.425000,0.441406,Yes,No

In [11]:
# Create dataframe for 2017 only

value = [2017]
df2017 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2017

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
11469,32,2017,QB,Offense,BAL,6000000,13800000,24550000,0.150,AFC,...,0,0.5625,2,395,303,92,0.298611,0.441406,No,No
11470,38,2017,QB,Offense,ARI,15500000,4250000,24125000,0.140,NFC,...,0,0.5000,3,295,361,-66,0.406250,0.488281,No,No
11471,29,2017,QB,Offense,WAS,23943600,0,23943600,0.136,NFC,...,0,0.4375,3,342,388,-46,0.428571,0.539062,No,No
11472,32,2017,QB,Offense,ATL,15750000,5600000,23750000,0.141,NFC,...,0,0.6250,3,353,315,38,0.475000,0.542969,Yes,No
11473,28,2017,OLB,Defense,KC,16350000,4100000,22100000,0.130,AFC,...,0,0.6250,1,415,339,76,0.481250,0.476562,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13587,22,2017,WR,Offense,BAL,27353,0,27353,0.000,AFC,...,0,0.5625,2,395,303,92,0.298611,0.441406,No,No
13588,23,2017,S,Defense,MIA,27353,0,27353,0.000,AFC,...,0,0.3750,3,281,393,-112,0.531250,0.542969,No,No
13589,24,2017,T,Offense,NYG,27353,0,27353,0.000,NFC,...,0,0.1875,4,246,388,-142,0.458333,0.531250,No,No
13590,28,2017,CB,Defense,GB,0,25788,25788,0.000,NFC,...,0,0.4375,3,320,384,-64,0.357143,0.539062,No,No
13591,25,2017,C,Offense,ATL,20470,0,20470,0.000,NFC,...,0,0.6250,3,353,315,38,0.475000,0.542969,Yes,No

In [12]:
# Create dataframe for 2018 only

value = [2018]
df2018 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2018

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
13592,27,2018,QB,Offense,SF,6200000,1400000,37000000,0.159,NFC,...,0,0.25000,3,342,435,-93,0.406250,0.500000,No,No
13593,30,2018,QB,Offense,DET,9500000,10000000,26500000,0.146,NFC,...,0,0.37500,4,324,360,-36,0.416667,0.496094,No,No
13594,27,2018,QB,Offense,LV/OAK,7400000,2500000,25000000,0.135,AFC,...,0,0.25000,4,290,467,-177,0.390625,0.542969,No,No
13595,33,2018,QB,Offense,BAL,12000000,8000000,24750000,0.137,AFC,...,0,0.62500,1,389,287,102,0.443750,0.488281,Yes,No
13596,29,2018,QB,Offense,IND,12000000,6400000,24400000,0.126,AFC,...,0,0.62500,2,433,344,89,0.456250,0.464844,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15688,24,2018,WR,Offense,CLE,28235,0,28235,0.000,AFC,...,1,0.46875,3,359,392,-33,0.410714,0.511719,No,No
15689,23,2018,CB,Defense,NYJ,28235,0,28235,0.000,AFC,...,0,0.25000,4,333,441,-108,0.437500,0.500000,No,No
15690,26,2018,WR,Offense,NYJ,28235,0,28235,0.000,AFC,...,0,0.25000,4,333,441,-108,0.437500,0.500000,No,No
15691,23,2018,WR,Offense,DEN,480000,3333,3333,0.000,AFC,...,0,0.37500,3,329,349,-20,0.458333,0.519531,No,No
15692,23,2018,C,Offense,BAL,480000,1000,1000,0.000,AFC,...,0,0.62500,1,389,287,102,0.443750,0.488281,Yes,No

In [13]:
# Create dataframe for 2019 only

value = [2019]
df2019 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2019

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
15693,31,2019,QB,Offense,DET,13500000,10000000,30700000,0.158,NFC,...,1,0.21875,4,341,423,-82,0.375000,0.503906,No,No
15694,36,2019,QB,Offense,GB,1100000,11500000,29672000,0.151,NFC,...,0,0.81250,1,376,313,63,0.423077,0.449219,Yes,No
15695,31,2019,QB,Offense,MIN,27500000,1000000,29000000,0.151,NFC,...,0,0.62500,2,407,303,104,0.350000,0.472656,Yes,No
15696,31,2019,QB,Offense,SEA,5000000,19200000,26286668,0.134,NFC,...,0,0.68750,2,405,398,7,0.460227,0.527344,Yes,No
15697,37,2019,QB,Offense,PIT,2500000,18700000,26200000,0.127,AFC,...,0,0.50000,2,289,303,-14,0.320312,0.500000,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17805,24,2019,CB,Defense,WAS,29118,0,29118,0.000,NFC,...,0,0.18750,4,266,435,-169,0.270833,0.500000,No,No
17806,24,2019,WR,Offense,WAS,29118,0,29118,0.000,NFC,...,0,0.18750,4,266,435,-169,0.270833,0.500000,No,No
17807,23,2019,DT,Defense,NYG,29118,0,29118,0.000,NFC,...,0,0.25000,3,341,451,-110,0.281250,0.468750,No,No
17808,24,2019,T,Offense,DEN,29118,0,29118,0.000,AFC,...,0,0.43750,2,282,316,-34,0.401786,0.507812,No,No
17809,23,2019,OLB,Defense,KC,320000,3333,3333,0.000,AFC,...,0,0.75000,1,451,308,143,0.473958,0.507812,Yes,Yes

In [14]:
# Create dataframe for 2020 only

value = [2020]
df2020 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2020

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
17810,27,2020,QB,Offense,DAL,31409000,0,31409000,0.144,NFC,...,0,0.3750,3,395,473,-78,0.333333,0.470703,No,No
17811,32,2020,QB,Offense,SEA,18000000,13000000,31000000,0.155,NFC,...,0,0.7500,1,459,371,88,0.403646,0.447266,Yes,No
17812,26,2020,QB,Offense,LAR/STL,1042682,5000000,28842682,0.142,NFC,...,0,0.6250,2,372,296,76,0.484375,0.494141,Yes,No
17813,29,2020,OLB,Defense,CHI,13300000,6800000,26600000,0.125,NFC,...,0,0.5000,2,372,370,2,0.335938,0.488281,Yes,No
17814,29,2020,QB,Offense,SF,23800000,1400000,26100000,0.126,NFC,...,0,0.3750,4,376,390,-14,0.447917,0.548828,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19844,26,2020,S,Defense,MIA,35882,0,35882,0.000,AFC,...,0,0.6250,2,404,338,66,0.346875,0.466797,No,No
19845,21,2020,SS,Defense,HOU,35882,0,35882,0.000,AFC,...,0,0.2500,3,384,464,-80,0.218750,0.541016,No,No
19846,24,2020,TE,Offense,NE,35882,0,35882,0.000,AFC,...,0,0.4375,3,326,353,-27,0.428571,0.527344,No,No
19847,22,2020,LB,Defense,NE,35882,0,35882,0.000,AFC,...,0,0.4375,3,326,353,-27,0.428571,0.527344,No,No
19848,23,2020,CB,Defense,ATL,33582,0,33582,0.000,NFC,...,0,0.2500,4,396,414,-18,0.390625,0.550781,No,No

In [15]:
# Create dataframe for 2021 only

value = [2021]
df2021 = pd.DataFrame(NFL_Merged_df[NFL_Merged_df.Year.isin(value)==True])

df2021

,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Conf,...,Ties,Win %,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won Superbowl
19849,33,2021,QB,Offense,SEA,19000000,13000000,32000000,0.174,NFC,...,0,0.411765,4,395,366,29,0.424370,0.519031,No,No
19850,33,2021,QB,Offense,MIN,21000000,10000000,31000000,0.166,NFC,...,0,0.470588,2,425,426,-1,0.433824,0.506920,No,No
19851,38,2021,QB,Offense,GB,1100000,16321568,27073568,0.145,NFC,...,0,0.764706,1,450,371,79,0.479638,0.479239,Yes,No
19852,36,2021,QB,Offense,ATL,2000000,9300000,26912500,0.146,NFC,...,0,0.411765,3,313,459,-146,0.315126,0.472318,No,No
19853,30,2021,QB,Offense,SF,24100000,1400000,26400000,0.135,NFC,...,0,0.588235,3,427,365,62,0.438235,0.500000,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21996,25,2021,WR,Offense,CAR,36666,0,36666,0.000,NFC,...,0,0.294118,4,304,404,-100,0.411765,0.508651,No,No
21997,23,2021,WR,Offense,HOU,36666,0,36666,0.000,AFC,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21998,23,2021,DT,Defense,HOU,36666,0,36666,0.000,AFC,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21999,23,2021,WR,Offense,NYJ,36666,0,36666,0.000,AFC,...,0,0.235294,4,310,504,-194,0.426471,0.512111,No,No
22000,26,2021,LB,Defense,HOU,36666,0,36666,0.000,AFC,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No

In [16]:
# Verify total row count

# 2011 - 1620 rows
# 2012 - 1812 rows
# 2013 - 1869 rows
# 2014 - 1993 rows
# 2015 - 2077 rows
# 2016 - 2098 rows
# 2017 - 2123 rows
# 2018 - 2101 rows
# 2019 - 2117 rows
# 2020 - 2039 rows
# 2021 - 2152 rows
# Total = 22001 rows
# NFL_merged = 22001 rows
# :)

# All Dataframes have 23 columns


# Note: It looks like the number of players has increased quite a bit over the past decade

## One Hot Encoding

In [17]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2011

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2011[column], prefix=column)
    df2011 = pd.merge(
        left=df2011,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2011 = df2011.drop(columns=column)
df2011

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
0,25,2011,14225000,0,17228125,0.134,8,8,0,0.5000,...,0,0,0,0,0,0,1,0,1,0
1,31,2011,11420000,2500000,16420000,0.134,2,14,0,0.1250,...,1,0,0,0,0,0,1,0,1,0
2,28,2011,2000000,5000000,16250000,0.133,8,8,0,0.5000,...,0,0,0,0,0,1,1,0,1,0
3,26,2011,13800000,0,16200000,0.135,10,6,0,0.6250,...,1,0,0,0,0,0,0,1,1,0
4,35,2011,3400000,4000000,16000000,0.130,2,14,0,0.1250,...,1,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615,23,2011,44117,0,44117,0.000,6,10,0,0.3750,...,0,0,0,0,0,0,1,0,1,0
1616,22,2011,44117,0,44117,0.000,9,7,0,0.5625,...,0,0,0,0,0,0,0,1,1,0
1617,25,2011,22059,0,22059,0.000,8,8,0,0.5000,...,0,0,0,0,0,0,1,0,1,0
1618,21,2011,22058,0,22058,0.000,3,13,0,0.1875,...,0,0,0,1,0,0,1,0,1,0
1619,23,2011,0,1666,1666,0.000,2,14,0,0.1250,...,0,0,0,0,0,1,1,0,1,0

In [18]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2012

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2012[column], prefix=column)
    df2012 = pd.merge(
        left=df2012,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2012 = df2012.drop(columns=column)
df2012

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
1620,32,2012,14035000,2500000,19035000,0.158,11,5,0,0.68750,...,1,0,0,0,0,0,0,1,1,0
1621,27,2012,10310000,0,19007500,0.158,7,8,1,0.46875,...,0,0,0,0,0,1,1,0,1,0
1622,36,2012,18000000,0,18000000,0.149,13,3,0,0.81250,...,0,1,0,0,0,0,0,1,1,0
1623,27,2012,1904000,13113332,17777332,0.147,11,4,1,0.71875,...,0,0,0,0,0,1,0,1,1,0
1624,28,2012,14000000,500000,15623000,0.130,13,3,0,0.81250,...,0,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3427,23,2012,45882,0,45882,0.000,5,11,0,0.31250,...,0,0,0,0,0,1,1,0,1,0
3428,24,2012,390000,0,22942,0.000,12,4,0,0.75000,...,1,0,0,0,0,0,0,1,1,0
3429,25,2012,22941,0,22941,0.000,2,14,0,0.12500,...,1,0,0,0,0,0,1,0,1,0
3430,24,2012,0,3334,3334,0.000,7,8,1,0.46875,...,0,0,0,0,0,1,1,0,1,0
3431,24,2012,1500,0,1500,0.000,7,9,0,0.43750,...,0,0,0,0,0,0,1,0,1,0

In [19]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2013

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2013[column], prefix=column)
    df2013 = pd.merge(
        left=df2013,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2013 = df2013.drop(columns=column)
df2013

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
3432,32,2013,13000000,2600000,20850000,0.167,7,9,0,0.43750,...,0,0,1,0,0,0,1,0,1,0
3433,25,2013,4000000,5500000,17820000,0.145,7,9,0,0.43750,...,0,0,0,1,0,0,1,0,1,0
3434,37,2013,15000000,0,17500000,0.124,13,3,0,0.81250,...,0,1,0,0,0,0,0,1,1,0
3435,34,2013,9750000,7400000,17400000,0.138,11,5,0,0.68750,...,0,0,0,0,1,0,0,1,1,0
3436,31,2013,14280612,2583344,17063956,0.130,5,10,1,0.34375,...,0,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5296,23,2013,405000,0,23823,0.000,2,14,0,0.12500,...,1,0,0,0,0,0,1,0,1,0
5297,23,2013,405000,0,23823,0.000,2,14,0,0.12500,...,1,0,0,0,0,0,1,0,1,0
5298,22,2013,405000,0,23823,0.000,11,5,0,0.68750,...,1,0,0,0,0,0,0,1,1,0
5299,23,2013,405000,0,23823,0.000,12,4,0,0.75000,...,0,0,0,0,0,0,0,1,1,0
5300,23,2013,405000,0,23823,0.000,8,7,1,0.53125,...,0,0,0,1,0,0,0,1,1,0

In [20]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2014

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2014[column], prefix=column)
    df2014 = pd.merge(
        left=df2014,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2014 = df2014.drop(columns=column)
df2014

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
5301,27,2014,12550000,0,22412500,0.170,11,5,0,0.6875,...,0,0,0,1,0,0,0,1,1,0
5302,26,2014,17500000,1100000,21295000,0.153,2,14,0,0.1250,...,0,0,0,0,1,0,1,0,1,0
5303,33,2014,15150000,0,20400000,0.155,6,10,0,0.3750,...,0,0,1,0,0,0,1,0,1,0
5304,32,2014,12100000,0,18895000,0.141,11,5,0,0.6875,...,0,0,0,0,0,0,0,1,1,0
5305,29,2014,1900000,3800000,18800000,0.125,9,7,0,0.5625,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7289,23,2014,420000,0,24705,0.000,6,10,0,0.3750,...,0,0,0,0,1,0,1,0,1,0
7290,24,2014,420000,0,24705,0.000,7,9,0,0.4375,...,0,0,0,0,0,0,1,0,1,0
7291,23,2014,420000,0,24705,0.000,7,9,0,0.4375,...,0,0,0,0,0,0,1,0,1,0
7292,23,2014,420000,0,24705,0.000,7,9,0,0.4375,...,0,0,0,1,0,0,1,0,1,0
7293,24,2014,0,1666,1666,0.000,12,4,0,0.7500,...,0,0,1,0,0,0,0,1,1,0

In [21]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2015

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2015[column], prefix=column)
    df2015 = pd.merge(
        left=df2015,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2015 = df2015.drop(columns=column)
df2015

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
7294,36,2015,13550000,7400000,23800000,0.164,7,9,0,0.4375,...,0,0,0,0,1,0,1,0,1,0
7295,34,2015,15000000,4500000,21166668,0.148,4,12,0,0.2500,...,0,1,0,0,0,0,1,0,1,0
7296,30,2015,12500000,3200000,20558000,0.142,7,9,0,0.4375,...,0,0,0,1,0,0,1,0,1,0
7297,29,2015,9750000,6000000,20020000,0.134,15,1,0,0.9375,...,0,0,0,0,1,0,0,1,1,0
7298,30,2015,11500000,5600000,19500000,0.133,8,8,0,0.5000,...,0,0,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9366,25,2015,25588,0,25588,0.000,7,9,0,0.4375,...,0,0,0,0,1,0,1,0,1,0
9367,22,2015,25588,0,25588,0.000,7,9,0,0.4375,...,0,0,0,0,0,1,1,0,1,0
9368,24,2015,25588,0,25588,0.000,7,9,0,0.4375,...,0,0,0,0,0,1,1,0,1,0
9369,24,2015,25588,0,25588,0.000,8,8,0,0.5000,...,0,0,0,0,1,0,1,0,1,0
9370,23,2015,25588,0,25588,0.000,5,11,0,0.3125,...,1,0,0,0,0,0,1,0,1,0

In [22]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2016

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2016[column], prefix=column)
    df2016 = pd.merge(
        left=df2016,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2016 = df2016.drop(columns=column)
df2016

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
9371,35,2016,17500000,6200000,24200000,0.145,11,5,0,0.68750,...,0,0,1,0,0,0,0,1,1,0
9372,34,2016,17750000,6200000,23950000,0.152,11,5,0,0.68750,...,0,0,0,0,0,0,0,1,1,0
9373,31,2016,15750000,5600000,23750000,0.150,11,5,0,0.68750,...,0,0,0,0,1,0,0,1,1,0
9374,31,2016,4000000,13800000,22550000,0.145,8,8,0,0.50000,...,0,0,0,0,0,0,1,0,1,0
9375,28,2016,17000000,5500000,22500000,0.143,9,7,0,0.56250,...,0,0,0,1,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11464,24,2016,26470,0,26470,0.000,7,9,0,0.43750,...,0,0,0,0,1,0,1,0,1,0
11465,23,2016,26470,0,26470,0.000,5,11,0,0.31250,...,0,0,0,0,0,0,1,0,1,0
11466,23,2016,26470,0,26470,0.000,5,11,0,0.31250,...,0,0,0,0,0,0,1,0,1,0
11467,26,2016,26470,0,26470,0.000,5,11,0,0.31250,...,0,1,0,0,0,0,1,0,1,0
11468,24,2016,26470,0,26470,0.000,10,5,1,0.65625,...,0,0,0,0,0,1,0,1,1,0

In [23]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2017

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2017[column], prefix=column)
    df2017 = pd.merge(
        left=df2017,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2017 = df2017.drop(columns=column)
df2017

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
11469,32,2017,6000000,13800000,24550000,0.150,9,7,0,0.5625,...,0,0,0,0,0,0,1,0,1,0
11470,38,2017,15500000,4250000,24125000,0.140,8,8,0,0.5000,...,0,0,0,0,0,1,1,0,1,0
11471,29,2017,23943600,0,23943600,0.136,7,9,0,0.4375,...,0,0,1,0,0,0,1,0,1,0
11472,32,2017,15750000,5600000,23750000,0.141,10,6,0,0.6250,...,0,0,0,0,1,0,0,1,1,0
11473,28,2017,16350000,4100000,22100000,0.130,10,6,0,0.6250,...,0,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13587,22,2017,27353,0,27353,0.000,9,7,0,0.5625,...,0,0,0,0,0,0,1,0,1,0
13588,23,2017,27353,0,27353,0.000,6,10,0,0.3750,...,0,0,0,0,0,0,1,0,1,0
13589,24,2017,27353,0,27353,0.000,3,13,0,0.1875,...,0,0,1,0,0,0,1,0,1,0
13590,28,2017,0,25788,25788,0.000,7,9,0,0.4375,...,0,0,0,1,0,0,1,0,1,0
13591,25,2017,20470,0,20470,0.000,10,6,0,0.6250,...,0,0,0,0,1,0,0,1,1,0

In [24]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2018

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2018[column], prefix=column)
    df2018 = pd.merge(
        left=df2018,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2018 = df2018.drop(columns=column)
df2018

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
13592,27,2018,6200000,1400000,37000000,0.159,4,12,0,0.25000,...,0,0,0,0,0,1,1,0,1,0
13593,30,2018,9500000,10000000,26500000,0.146,6,10,0,0.37500,...,0,0,0,1,0,0,1,0,1,0
13594,27,2018,7400000,2500000,25000000,0.135,4,12,0,0.25000,...,0,1,0,0,0,0,1,0,1,0
13595,33,2018,12000000,8000000,24750000,0.137,10,6,0,0.62500,...,0,0,0,0,0,0,0,1,1,0
13596,29,2018,12000000,6400000,24400000,0.126,10,6,0,0.62500,...,1,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15688,24,2018,28235,0,28235,0.000,7,8,1,0.46875,...,0,0,0,0,0,0,1,0,1,0
15689,23,2018,28235,0,28235,0.000,4,12,0,0.25000,...,0,0,0,0,0,0,1,0,1,0
15690,26,2018,28235,0,28235,0.000,4,12,0,0.25000,...,0,0,0,0,0,0,1,0,1,0
15691,23,2018,480000,3333,3333,0.000,6,10,0,0.37500,...,0,1,0,0,0,0,1,0,1,0
15692,23,2018,480000,1000,1000,0.000,10,6,0,0.62500,...,0,0,0,0,0,0,0,1,1,0

In [25]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2019

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2019[column], prefix=column)
    df2019 = pd.merge(
        left=df2019,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2019 = df2019.drop(columns=column)
df2019

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
15693,31,2019,13500000,10000000,30700000,0.158,3,12,1,0.21875,...,0,0,0,1,0,0,1,0,1,0
15694,36,2019,1100000,11500000,29672000,0.151,13,3,0,0.81250,...,0,0,0,1,0,0,0,1,1,0
15695,31,2019,27500000,1000000,29000000,0.151,10,6,0,0.62500,...,0,0,0,1,0,0,0,1,1,0
15696,31,2019,5000000,19200000,26286668,0.134,11,5,0,0.68750,...,0,0,0,0,0,1,0,1,1,0
15697,37,2019,2500000,18700000,26200000,0.127,8,8,0,0.50000,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17805,24,2019,29118,0,29118,0.000,3,13,0,0.18750,...,0,0,1,0,0,0,1,0,1,0
17806,24,2019,29118,0,29118,0.000,3,13,0,0.18750,...,0,0,1,0,0,0,1,0,1,0
17807,23,2019,29118,0,29118,0.000,4,12,0,0.25000,...,0,0,1,0,0,0,1,0,1,0
17808,24,2019,29118,0,29118,0.000,7,9,0,0.43750,...,0,1,0,0,0,0,1,0,1,0
17809,23,2019,320000,3333,3333,0.000,12,4,0,0.75000,...,0,1,0,0,0,0,0,1,0,1

In [26]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2020

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2020[column], prefix=column)
    df2020 = pd.merge(
        left=df2020,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2020 = df2020.drop(columns=column)
df2020

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
17810,27,2020,31409000,0,31409000,0.144,6,10,0,0.3750,...,0,0,1,0,0,0,1,0,1,0
17811,32,2020,18000000,13000000,31000000,0.155,12,4,0,0.7500,...,0,0,0,0,0,1,0,1,1,0
17812,26,2020,1042682,5000000,28842682,0.142,10,6,0,0.6250,...,0,0,0,0,0,1,0,1,1,0
17813,29,2020,13300000,6800000,26600000,0.125,8,8,0,0.5000,...,0,0,0,1,0,0,0,1,1,0
17814,29,2020,23800000,1400000,26100000,0.126,6,10,0,0.3750,...,0,0,0,0,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19844,26,2020,35882,0,35882,0.000,10,6,0,0.6250,...,0,0,0,0,0,0,1,0,1,0
19845,21,2020,35882,0,35882,0.000,4,12,0,0.2500,...,1,0,0,0,0,0,1,0,1,0
19846,24,2020,35882,0,35882,0.000,7,9,0,0.4375,...,0,0,0,0,0,0,1,0,1,0
19847,22,2020,35882,0,35882,0.000,7,9,0,0.4375,...,0,0,0,0,0,0,1,0,1,0
19848,23,2020,33582,0,33582,0.000,4,12,0,0.2500,...,0,0,0,0,1,0,1,0,1,0

In [27]:
# Using get_dummies and a for loop one hot encode each categorical column and delete the original data - 2021

categorical_columns = ['Pos', 'Cat_POS', 'Team',
                       'Conf', 'Division', 'Playoff', 'Won Superbowl']
for column in categorical_columns:
    tempdf = pd.get_dummies(df2021[column], prefix=column)
    df2021 = pd.merge(
        left=df2021,
        right=tempdf,
        left_index=True,
        right_index=True,
    )
    df2021 = df2021.drop(columns=column)
df2021

,Age,Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Wins,Losses,Ties,Win %,...,Division_AFC South,Division_AFC West,Division_NFC East,Division_NFC North,Division_NFC South,Division_NFC West,Playoff_No,Playoff_Yes,Won Superbowl_No,Won Superbowl_Yes
19849,33,2021,19000000,13000000,32000000,0.174,7,10,0,0.411765,...,0,0,0,0,0,1,1,0,1,0
19850,33,2021,21000000,10000000,31000000,0.166,8,9,0,0.470588,...,0,0,0,1,0,0,1,0,1,0
19851,38,2021,1100000,16321568,27073568,0.145,13,4,0,0.764706,...,0,0,0,1,0,0,0,1,1,0
19852,36,2021,2000000,9300000,26912500,0.146,7,10,0,0.411765,...,0,0,0,0,1,0,1,0,1,0
19853,30,2021,24100000,1400000,26400000,0.135,10,7,0,0.588235,...,0,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21996,25,2021,36666,0,36666,0.000,5,12,0,0.294118,...,0,0,0,0,1,0,1,0,1,0
21997,23,2021,36666,0,36666,0.000,4,13,0,0.235294,...,1,0,0,0,0,0,1,0,1,0
21998,23,2021,36666,0,36666,0.000,4,13,0,0.235294,...,1,0,0,0,0,0,1,0,1,0
21999,23,2021,36666,0,36666,0.000,4,13,0,0.235294,...,0,0,0,0,0,0,1,0,1,0
22000,26,2021,36666,0,36666,0.000,4,13,0,0.235294,...,1,0,0,0,0,0,1,0,1,0

In [28]:
# export to csv

df2011_path = "df2011.csv"
df2011.to_csv(df2011_path, index=False)

df2012_path = "df2012.csv"
df2012.to_csv(df2012_path, index=False)

df2013_path = "df2013.csv"
df2013.to_csv(df2013_path, index=False)

df2014_path = "df2014.csv"
df2014.to_csv(df2014_path, index=False)

df2015_path = "df2015.csv"
df2015.to_csv(df2015_path, index=False)

df2016_path = "df2016.csv"
df2016.to_csv(df2016_path, index=False)

df2017_path = "df2017.csv"
df2017.to_csv(df2017_path, index=False)

df2018_path = "df2018.csv"
df2018.to_csv(df2018_path, index=False)

df2019_path = "df2019.csv"
df2019.to_csv(df2019_path, index=False)

df2020_path = "df2020.csv"
df2020.to_csv(df2020_path, index=False)

df2021_path = "df2021.csv"
df2021.to_csv(df2021_path, index=False)