In [1]:
# Import Dependencies

import pandas as pd
import numpy as np

## Player Financials

In [2]:
# load and read csv file into DataFrame

financials_to_load = "../Resources/NFL_Yearly_Breakdown_combined.csv"
financials_df = pd.read_csv(financials_to_load)
financials_df

,Rank,Player,Year,Pos,Team,Draft Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Cash,AAV,CONT YR,CONT VALUE,Earnings,FA Year,Sign Year,Sign Age,Age,Unnamed: 19
0,NaN,Mark Sanchez,2011,QB,NYJ,2009,"$14,225,000",$0,"$17,228,125",0.134,"$14,725,000","$10,100,000",5,"$50,500,000","$41,392,500",2014,2009,22,25,NaN
1,NaN,Dwight Freeney,2011,OLB,IND,2002,"$11,420,000","$2,500,000","$16,420,000",0.134,"$11,420,000","$12,000,000",6,"$72,000,000","$72,137,572",2013,2007,26,31,NaN
2,NaN,Larry Fitzgerald,2011,WR,ARI,2004,"$2,000,000","$5,000,000","$16,250,000",0.133,"$20,000,000","$16,142,857",7,"$113,000,000","$73,782,500",2019,2011,27,28,NaN
3,NaN,Mario Williams,2011,DE,HOU,2006,"$13,800,000",$0,"$16,200,000",0.135,"$13,800,000","$9,000,000",6,"$54,000,000","$44,500,000",2012,2006,20,26,NaN
4,NaN,Peyton Manning,2011,QB,IND,1998,"$3,400,000","$4,000,000","$16,000,000",0.130,"$26,400,000","$18,000,000",5,"$90,000,000","$171,732,000",2016,2011,34,35,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24852,NaN,Bradley Roby,2024,CB,NO,2014,$0,$0,"$169,475",0.001,$0,"$10,500,000",3,"$31,500,000","$54,970,752",2023,2020,27,32,NaN
24853,NaN,Jesse James,2024,TE,CHI,2015,$0,"$162,500","$162,500",0.001,$0,"$1,650,000",1,"$1,650,000","$17,707,976",2022,2021,26,30,NaN
24854,NaN,Damien Williams,2024,RB,CHI,-99,$0,"$125,000","$125,000",0.000,$0,"$1,500,000",1,"$1,500,000","$8,972,000",2022,2021,28,32,NaN
24855,NaN,Tanoh Kpassagnon,2024,DE,NO,2017,$0,"$100,000","$100,000",0.000,$0,"$2,250,000",2,"$4,500,000","$9,290,468",2023,2021,26,30,NaN
24856,NaN,"Odell Beckham, Jr.",2024,WR,LAR,2014,$0,"$100,000","$100,000",0.000,$0,"$1,250,000",1,"$1,250,000","$82,896,476",2022,2021,28,32,NaN

In [3]:
# Look for missing values

print(financials_df.count())
financials_df.isnull()

Rank                0
Player          24857
Year            24857
Pos             24857
Team            24857
Draft Year      24857
BaseSalary      24857
SigningBonus    24857
Cap Hit         24857
Salary%         24857
Cash            24857
AAV             24857
CONT YR         24857
CONT VALUE      24857
Earnings        24857
FA Year         24857
Sign Year       24857
Sign Age        24857
Age             24857
Unnamed: 19         0
dtype: int64

,Rank,Player,Year,Pos,Team,Draft Year,BaseSalary,SigningBonus,Cap Hit,Salary%,Cash,AAV,CONT YR,CONT VALUE,Earnings,FA Year,Sign Year,Sign Age,Age,Unnamed: 19
0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24852,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
24853,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
24854,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
24855,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
24856,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [4]:
# Drop columns

financials_df = financials_df.drop(columns=["Rank","Unnamed: 19", "FA Year", 
        "Sign Year", "Sign Age","Cash","Draft Year","AAV","CONT YR","CONT VALUE","Earnings"])
financials_df

,Player,Year,Pos,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Age
0,Mark Sanchez,2011,QB,NYJ,"$14,225,000",$0,"$17,228,125",0.134,25
1,Dwight Freeney,2011,OLB,IND,"$11,420,000","$2,500,000","$16,420,000",0.134,31
2,Larry Fitzgerald,2011,WR,ARI,"$2,000,000","$5,000,000","$16,250,000",0.133,28
3,Mario Williams,2011,DE,HOU,"$13,800,000",$0,"$16,200,000",0.135,26
4,Peyton Manning,2011,QB,IND,"$3,400,000","$4,000,000","$16,000,000",0.130,35
...,...,...,...,...,...,...,...,...,...
24852,Bradley Roby,2024,CB,NO,$0,$0,"$169,475",0.001,32
24853,Jesse James,2024,TE,CHI,$0,"$162,500","$162,500",0.001,30
24854,Damien Williams,2024,RB,CHI,$0,"$125,000","$125,000",0.000,32
24855,Tanoh Kpassagnon,2024,DE,NO,$0,"$100,000","$100,000",0.000,30
24856,"Odell Beckham, Jr.",2024,WR,LAR,$0,"$100,000","$100,000",0.000,32

In [5]:
# Add column for Catagory of position (offence, defence, special teams)

Positions = [
    (financials_df["Pos"] == "C"),
    (financials_df["Pos"] == "FB"),
    (financials_df["Pos"] == "G"),
    (financials_df["Pos"] == "LT"),
    (financials_df["Pos"] == "QB"),
    (financials_df["Pos"] == "RB"),
    (financials_df["Pos"] == "RT"),
    (financials_df["Pos"] == "T"),
    (financials_df["Pos"] == "TE"),
    (financials_df["Pos"] == "WR"),
    (financials_df["Pos"] == "CB"),
    (financials_df["Pos"] == "DE"),
    (financials_df["Pos"] == "DT"),
    (financials_df["Pos"] == "FS"),
    (financials_df["Pos"] == "ILB"),
    (financials_df["Pos"] == "LB"),
    (financials_df["Pos"] == "OLB"),
    (financials_df["Pos"] == "S"),
    (financials_df["Pos"] == "SS"),
    (financials_df["Pos"] == "K"),
    (financials_df["Pos"] == "LS"),
    (financials_df["Pos"] == "P")
]
# Create a list of the values to assign for each condition
values = ["Offense", "Offense", "Offense", "Offense", "Offense", "Offense", "Offense", "Offense", "Offense", "Offense",
          "Defense", "Defense", "Defense", "Defense", "Defense", "Defense", "Defense", "Defense", "Defense","Special Teams",
          "Special Teams","Special Teams"]

# create a new column and use np.select to assign values for winning column
financials_df["Cat_POS"] = np.select(Positions, values)

# display updated DataFrame
financials_df.head(32)

,Player,Year,Pos,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Age,Cat_POS
0,Mark Sanchez,2011,QB,NYJ,"$14,225,000",$0,"$17,228,125",0.134,25,Offense
1,Dwight Freeney,2011,OLB,IND,"$11,420,000","$2,500,000","$16,420,000",0.134,31,Defense
2,Larry Fitzgerald,2011,WR,ARI,"$2,000,000","$5,000,000","$16,250,000",0.133,28,Offense
3,Mario Williams,2011,DE,HOU,"$13,800,000",$0,"$16,200,000",0.135,26,Defense
4,Peyton Manning,2011,QB,IND,"$3,400,000","$4,000,000","$16,000,000",0.130,35,Offense
5,Joe Thomas,2011,LT,CLE,"$8,000,000","$2,260,000","$15,960,000",0.123,27,Offense
6,Elvis Dumervil,2011,OLB,DEN,"$14,000,000","$500,000","$15,623,000",0.107,27,Defense
7,Michael Vick,2011,QB,PHI,"$10,000,000","$1,400,000","$14,400,000",0.110,31,Offense
8,Calvin Johnson,2011,WR,DET,"$8,875,000","$2,800,000","$14,175,000",0.117,26,Offense
9,Eli Manning,2011,QB,NYG,"$8,500,000","$2,600,000","$14,100,000",0.116,30,Offense
10,Philip Rivers,2011,QB,SD,"$8,400,000","$3,910,000","$13,510,000",0.112,30,Offense
11,Matt Ryan,2011,QB,ATL,"$11,250,000","$2,000,000","$13,250,000",0.110,26,Offense
12,Adrian Peterson,2011,RB,MIN,"$8,250,000","$2,900,000","$12,955,000",0.106,26,Offense
13,Tom Brady,2011,QB,NE,"$5,750,000","$3,200,000","$12,950,000",0.102,34,Offense
14,Jake Long,2011,LT,MIA,"$11,200,000",$0,"$12,800,000",0.099,26,Offense
15,Drew Brees,2011,QB,NO,"$7,393,500",$0,"$12,574,700",0.101,32,Offense
16,Paul Soliai,2011,DT,MIA,"$12,476,000",$0,"$12,476,000",0.097,28,Defense
17,Sam Bradford,2011,QB,STL,"$450,000","$3,595,000","$12,465,000",0.101,24,Offense
18,Ndamukong Suh,2011,DT,DET,"$1,239,706",$0,"$11,904,706",0.098,24,Defense
19,Brian Urlacher,2011,LB,CHI,"$8,025,000","$1,200,000","$11,825,000",0.092,33,Defense
20,Jason Smith,2011,LT,STL,"$8,500,000",$0,"$11,767,500",0.095,25,Offense
21,Jared Allen,2011,DE,MIN,"$8,979,438","$2,583,344","$11,762,782",0.096,29,Defense
22,Vincent Jackson,2011,WR,SD,"$11,424,000",$0,"$11,424,000",0.095,28,Offense
23,Darrius Heyward-Bey,2011,WR,OAK,"$1,000,000",$0,"$11,415,000",0.093,24,Offense
24,Tyson Jackson,2011,DE,KC,"$1,790,000",$0,"$11,340,000",0.079,25,Defense
25,Ben Roethlisberger,2011,QB,PIT,"$6,000,000","$4,200,000","$11,320,000",0.094,29,Offense
26,Darrelle Revis,2011,CB,NYJ,"$6,000,000","$783,416","$11,265,916",0.088,26,Defense
27,Champ Bailey,2011,CB,DEN,"$6,500,000",$0,"$11,000,000",0.075,33,Defense
28,Darren McFadden,2011,RB,OAK,"$7,045,000",$0,"$10,873,833",0.088,24,Offense
29,Brandon Marshall,2011,WR,MIA,"$6,500,000","$1,100,000","$10,800,000",0.084,27,Offense
30,Marcus McNeill,2011,T,SD,"$10,000,000","$358,200","$10,358,200",0.086,28,Offense
31,John Abraham,2011,OLB,ATL,"$8,000,000","$2,083,333","$10,083,333",0.084,33,Defense

In [6]:
# Drop rows with future years

values = [2022, 2023, 2024]
financials_df = financials_df[financials_df.Year.isin(values)==False]
financials_df

,Player,Year,Pos,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Age,Cat_POS
0,Mark Sanchez,2011,QB,NYJ,"$14,225,000",$0,"$17,228,125",0.134,25,Offense
1,Dwight Freeney,2011,OLB,IND,"$11,420,000","$2,500,000","$16,420,000",0.134,31,Defense
2,Larry Fitzgerald,2011,WR,ARI,"$2,000,000","$5,000,000","$16,250,000",0.133,28,Offense
3,Mario Williams,2011,DE,HOU,"$13,800,000",$0,"$16,200,000",0.135,26,Defense
4,Peyton Manning,2011,QB,IND,"$3,400,000","$4,000,000","$16,000,000",0.130,35,Offense
...,...,...,...,...,...,...,...,...,...,...
21996,Stephen Sullivan,2021,WR,CAR,"$36,666",$0,"$36,666",0.000,25,Offense
21997,Jalen Camp,2021,WR,HOU,"$36,666",$0,"$36,666",0.000,23,Offense
21998,Michael Dwumfour,2021,DT,HOU,"$36,666",$0,"$36,666",0.000,23,Defense
21999,Tarik Black,2021,WR,NYJ,"$36,666",$0,"$36,666",0.000,23,Offense
22000,Connor Strachan,2021,LB,HOU,"$36,666",$0,"$36,666",0.000,26,Defense

In [7]:
# Check again for missing values

print(financials_df.count())
financials_df.isnull()

Player          22001
Year            22001
Pos             22001
Team            22001
BaseSalary      22001
SigningBonus    22001
Cap Hit         22001
Salary%         22001
Age             22001
Cat_POS         22001
dtype: int64

,Player,Year,Pos,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Age,Cat_POS
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
21996,False,False,False,False,False,False,False,False,False,False
21997,False,False,False,False,False,False,False,False,False,False
21998,False,False,False,False,False,False,False,False,False,False
21999,False,False,False,False,False,False,False,False,False,False
22000,False,False,False,False,False,False,False,False,False,False

In [8]:
# Combine the records of renamed teams; look at random selection

financials_df["Team"].replace({"LAR":"LAR/STL", "STL":"LAR/STL", "JAC":"JAX","LV": "LV/OAK","OAK": "LV/OAK", "SD":"LAC/SD", "LAC":"LAC/SD"},inplace=True)
financials_df.sample(25)

C:\Users\dpren\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

,Player,Year,Pos,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Age,Cat_POS
2479,Matt Shaughnessy,2012,DE,LV/OAK,"$565,000","$213,062","$778,062",0.007,26,Defense
4899,Rokevious Watkins,2013,G,KC,"$405,000","$30,000","$435,000",0.003,24,Offense
12684,Jaleel Johnson,2017,DT,MIN,"$465,000","$169,588","$634,588",0.004,23,Defense
8455,Andre Ellington,2015,RB,ARI,"$585,000","$25,966","$610,966",0.004,26,Offense
6250,Chris Givens,2014,WR,LAR/STL,"$570,000","$124,257","$694,257",0.005,25,Offense
13096,Matt Breida,2017,RB,SF,"$465,000","$1,666","$466,666",0.002,22,Offense
905,Vladimir Ducasse,2011,G,NYJ,"$405,000","$256,250","$661,250",0.005,24,Offense
19367,Tremon Smith,2020,CB,IND,"$661,770",$0,"$661,770",0.003,24,Defense
13775,Prince Amukamara,2018,CB,CHI,"$3,500,000","$1,000,000","$7,500,000",0.041,29,Defense
3956,Star Lotulelei,2013,DT,CAR,"$405,000","$1,341,273","$1,746,273",0.014,24,Defense
11591,Buster Skrine,2017,CB,NYJ,"$6,000,000","$1,250,000","$8,500,000",0.051,28,Defense
1199,Alexander Green,2011,RB,GB,"$375,000","$128,750","$503,750",0.004,23,Offense
10390,Tyler Kroft,2016,TE,CIN,"$540,500","$161,944","$712,444",0.004,24,Offense
752,Rock Cartwright,2011,RB,LV/OAK,"$810,000","$100,000","$910,000",0.007,32,Offense
18753,Dorian O'Daniel,2020,OLB,KC,"$750,000","$190,379","$963,879",0.004,26,Defense
9309,Dezmin Lewis,2015,WR,BUF,"$51,176",$0,"$51,176",0.000,23,Offense
6101,Derek Carr,2014,QB,LV/OAK,"$420,000","$556,691","$976,691",0.008,23,Offense
9373,Matt Ryan,2016,QB,ATL,"$15,750,000","$5,600,000","$23,750,000",0.150,31,Offense
15120,Shalom Luani,2018,S,SEA,"$522,353",$0,"$522,352",0.003,24,Defense
7901,B.J. Raji,2015,DT,GB,"$1,150,000","$500,000","$1,750,000",0.012,29,Defense
19105,Zach Pascal,2020,WR,IND,"$750,000",$0,"$750,000",0.003,26,Offense
15284,Shaun Wilson,2018,RB,TB,"$431,814","$3,333","$435,147",0.002,23,Offense
15844,Kenny Moore,2019,CB,IND,"$1,000,000",$0,"$9,000,000",0.038,24,Defense
10209,Tavon Wilson,2016,SS,DET,"$800,000","$250,000","$1,050,000",0.007,26,Defense
9699,Mike Evans,2016,WR,TB,"$600,000","$2,240,273","$3,990,410",0.025,23,Offense

In [9]:
# Check datatypes
financials_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22001 entries, 0 to 22000
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player        22001 non-null  object
 1   Year          22001 non-null  int64
 2   Pos           22001 non-null  object
 3   Team          22001 non-null  object
 4   BaseSalary    22001 non-null  object
 5   SigningBonus  22001 non-null  object
 6   Cap Hit       22001 non-null  object
 7   Salary%       22001 non-null  float64
 8   Age           22001 non-null  int64
 9   Cat_POS       22001 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 1.8+ MB

In [10]:
# changed datatype for 3 columns to integers (base salary, signing bonus, cap hit)

financials_df["BaseSalary"] = financials_df["BaseSalary"].str.replace(',', '')
financials_df["BaseSalary"] = financials_df["BaseSalary"].str.replace('$', '')
financials_df["BaseSalary"] = financials_df["BaseSalary"].astype(int)

financials_df["SigningBonus"] = financials_df["SigningBonus"].str.replace(',', '')
financials_df["SigningBonus"] = financials_df["SigningBonus"].str.replace('$', '')
financials_df["SigningBonus"] = financials_df["SigningBonus"].astype(int)

financials_df["Cap Hit"] = financials_df["Cap Hit"].str.replace(',', '')
financials_df["Cap Hit"] = financials_df["Cap Hit"].str.replace('$', '')
financials_df["Cap Hit"] = financials_df["Cap Hit"].astype(int)


financials_df.info()
financials_df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22001 entries, 0 to 22000
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Player        22001 non-null  object
 1   Year          22001 non-null  int64
 2   Pos           22001 non-null  object
 3   Team          22001 non-null  object
 4   BaseSalary    22001 non-null  int32
 5   SigningBonus  22001 non-null  int32
 6   Cap Hit       22001 non-null  int32
 7   Salary%       22001 non-null  float64
 8   Age           22001 non-null  int64
 9   Cat_POS       22001 non-null  object
dtypes: float64(1), int32(3), int64(2), object(4)
memory usage: 1.6+ MB

C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  financials_df["BaseSalary"] = financials_df["BaseSalary"].str.replace(',', '')
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  financials_df["BaseSalary"] = financials_df["BaseSalary"].str.replace('$', '')
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  financials_df["BaseSalary"] = financials_df["BaseSalary"].str.replace('$', '')
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  financials_df["BaseSalary"] = financials_df["BaseSalary"].astype(int)
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  financials_df["SigningBonus"] = financials_df["SigningBonus"].str.replace(',', '')
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:8: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  financials_df["SigningBonus"] = financials_df["SigningBonus"].str.replace('$', '')
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  financials_df["SigningBonus"] = financials_df["SigningBonus"].str.replace('$', '')
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  financials_df["SigningBonus"] = financials_df["SigningBonus"].astype(int)
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  financials_df["Cap Hit"] = financials_df["Cap Hit"].str.replace(',', '')
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:12: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  financials_df["Cap Hit"] = financials_df["Cap Hit"].str.replace('$', '')
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  financials_df["Cap Hit"] = financials_df["Cap Hit"].str.replace('$', '')
C:\Users\dpren\AppData\Local\Temp/ipykernel_18852/4047830758.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  financials_df["Cap Hit"] = financials_df["Cap Hit"].astype(int)

,Player,Year,Pos,Team,BaseSalary,SigningBonus,Cap Hit,Salary%,Age,Cat_POS
0,Mark Sanchez,2011,QB,NYJ,14225000,0,17228125,0.134,25,Offense
1,Dwight Freeney,2011,OLB,IND,11420000,2500000,16420000,0.134,31,Defense
2,Larry Fitzgerald,2011,WR,ARI,2000000,5000000,16250000,0.133,28,Offense
3,Mario Williams,2011,DE,HOU,13800000,0,16200000,0.135,26,Defense
4,Peyton Manning,2011,QB,IND,3400000,4000000,16000000,0.130,35,Offense

In [11]:
financials_df = financials_df.rename(columns={"Cap Hit":"Cap_Hit"})
financials_df

,Player,Year,Pos,Team,BaseSalary,SigningBonus,Cap_Hit,Salary%,Age,Cat_POS
0,Mark Sanchez,2011,QB,NYJ,14225000,0,17228125,0.134,25,Offense
1,Dwight Freeney,2011,OLB,IND,11420000,2500000,16420000,0.134,31,Defense
2,Larry Fitzgerald,2011,WR,ARI,2000000,5000000,16250000,0.133,28,Offense
3,Mario Williams,2011,DE,HOU,13800000,0,16200000,0.135,26,Defense
4,Peyton Manning,2011,QB,IND,3400000,4000000,16000000,0.130,35,Offense
...,...,...,...,...,...,...,...,...,...,...
21996,Stephen Sullivan,2021,WR,CAR,36666,0,36666,0.000,25,Offense
21997,Jalen Camp,2021,WR,HOU,36666,0,36666,0.000,23,Offense
21998,Michael Dwumfour,2021,DT,HOU,36666,0,36666,0.000,23,Defense
21999,Tarik Black,2021,WR,NYJ,36666,0,36666,0.000,23,Offense
22000,Connor Strachan,2021,LB,HOU,36666,0,36666,0.000,26,Defense

In [12]:
# Export financial Dataframe to csv

financials_df_path = "../Resources/financials_df.csv"
financials_df.to_csv(financials_df_path, index=False)

## Team Standings

In [13]:
# load and read csv file into DataFrame

standings_to_load = "../Resources/nfl_standings.csv"
nfl_standings_df = pd.read_csv(standings_to_load)
nfl_standings_df

,season,conf,division,team,wins,losses,ties,pct,div_rank,scored,allowed,net,sov,sos,seed,playoff
0,2021,AFC,AFC East,BUF,11,6,0,0.647059,1,483,289,194,0.427807,0.472318,3.0,LostDV
1,2021,AFC,AFC East,MIA,9,8,0,0.529412,3,341,373,-32,0.379085,0.463668,NaN,NaN
2,2021,AFC,AFC East,NE,10,7,0,0.588235,2,462,303,159,0.394118,0.480969,6.0,LostWC
3,2021,AFC,AFC East,NYJ,4,13,0,0.235294,4,310,504,-194,0.426471,0.512111,NaN,NaN
4,2021,AFC,AFC North,BAL,8,9,0,0.470588,4,387,392,-5,0.459559,0.531142,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,2002,NFC,NFC South,TB,12,4,0,0.750000,1,346,196,150,0.427083,0.476562,2.0,WonSB
636,2002,NFC,NFC West,ARI,5,11,0,0.312500,4,262,417,-155,0.400000,0.500000,NaN,NaN
637,2002,NFC,NFC West,SEA,7,9,0,0.437500,3,355,369,-14,0.428571,0.503906,NaN,NaN
638,2002,NFC,NFC West,SF,10,6,0,0.625000,1,367,351,16,0.450000,0.503906,4.0,LostDV
639,2002,NFC,NFC West,STL,7,9,0,0.437500,2,316,369,-53,0.446429,0.507812,NaN,NaN

In [14]:
# Review dataframe

nfl_standings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   season    640 non-null    int64
 1   conf      640 non-null    object
 2   division  640 non-null    object
 3   team      640 non-null    object
 4   wins      640 non-null    int64
 5   losses    640 non-null    int64
 6   ties      640 non-null    int64
 7   pct       640 non-null    float64
 8   div_rank  640 non-null    int64
 9   scored    640 non-null    int64
 10  allowed   640 non-null    int64
 11  net       640 non-null    int64
 12  sov       640 non-null    float64
 13  sos       640 non-null    float64
 14  seed      244 non-null    float64
 15  playoff   243 non-null    object
dtypes: float64(4), int64(8), object(4)
memory usage: 80.1+ KB

In [15]:
# Change column headings (to be consistent with financial dataframe)

nfl_standings_df = nfl_standings_df.rename(
    columns={"season": "Year", "pct": "Win%","conf":"Conf","division":"Division",
    "team":"Team","wins":"Wins","losses":"Losses","ties":"Ties","div_rank":"Div_Rank",
    "scored":"Scored","allowed":"Allowed","net":"Net","sov":"SOV","sos":"SOS","playoff":"Playoff"})
nfl_standings_df

,Year,Conf,Division,Team,Wins,Losses,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,seed,Playoff
0,2021,AFC,AFC East,BUF,11,6,0,0.647059,1,483,289,194,0.427807,0.472318,3.0,LostDV
1,2021,AFC,AFC East,MIA,9,8,0,0.529412,3,341,373,-32,0.379085,0.463668,NaN,NaN
2,2021,AFC,AFC East,NE,10,7,0,0.588235,2,462,303,159,0.394118,0.480969,6.0,LostWC
3,2021,AFC,AFC East,NYJ,4,13,0,0.235294,4,310,504,-194,0.426471,0.512111,NaN,NaN
4,2021,AFC,AFC North,BAL,8,9,0,0.470588,4,387,392,-5,0.459559,0.531142,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,2002,NFC,NFC South,TB,12,4,0,0.750000,1,346,196,150,0.427083,0.476562,2.0,WonSB
636,2002,NFC,NFC West,ARI,5,11,0,0.312500,4,262,417,-155,0.400000,0.500000,NaN,NaN
637,2002,NFC,NFC West,SEA,7,9,0,0.437500,3,355,369,-14,0.428571,0.503906,NaN,NaN
638,2002,NFC,NFC West,SF,10,6,0,0.625000,1,367,351,16,0.450000,0.503906,4.0,LostDV
639,2002,NFC,NFC West,STL,7,9,0,0.437500,2,316,369,-53,0.446429,0.507812,NaN,NaN

In [16]:
# Combine records of renamed teams

nfl_standings_df["Team"].replace({"LA": "LAR/STL", "STL": "LAR/STL", "LV": "LV/OAK",
                                 "OAK": "LV/OAK", "SD": "LAC/SD", "LAC": "LAC/SD"}, inplace=True),
nfl_standings_df

,Year,Conf,Division,Team,Wins,Losses,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,seed,Playoff
0,2021,AFC,AFC East,BUF,11,6,0,0.647059,1,483,289,194,0.427807,0.472318,3.0,LostDV
1,2021,AFC,AFC East,MIA,9,8,0,0.529412,3,341,373,-32,0.379085,0.463668,NaN,NaN
2,2021,AFC,AFC East,NE,10,7,0,0.588235,2,462,303,159,0.394118,0.480969,6.0,LostWC
3,2021,AFC,AFC East,NYJ,4,13,0,0.235294,4,310,504,-194,0.426471,0.512111,NaN,NaN
4,2021,AFC,AFC North,BAL,8,9,0,0.470588,4,387,392,-5,0.459559,0.531142,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,2002,NFC,NFC South,TB,12,4,0,0.750000,1,346,196,150,0.427083,0.476562,2.0,WonSB
636,2002,NFC,NFC West,ARI,5,11,0,0.312500,4,262,417,-155,0.400000,0.500000,NaN,NaN
637,2002,NFC,NFC West,SEA,7,9,0,0.437500,3,355,369,-14,0.428571,0.503906,NaN,NaN
638,2002,NFC,NFC West,SF,10,6,0,0.625000,1,367,351,16,0.450000,0.503906,4.0,LostDV
639,2002,NFC,NFC West,LAR/STL,7,9,0,0.437500,2,316,369,-53,0.446429,0.507812,NaN,NaN

In [17]:
# Drop data (rows) prior to 2011,

nfl_standings_df.drop(
    nfl_standings_df.loc[nfl_standings_df["Year"] < 2011].index, inplace=True)
nfl_standings_df

,Year,Conf,Division,Team,Wins,Losses,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,seed,Playoff
0,2021,AFC,AFC East,BUF,11,6,0,0.647059,1,483,289,194,0.427807,0.472318,3.0,LostDV
1,2021,AFC,AFC East,MIA,9,8,0,0.529412,3,341,373,-32,0.379085,0.463668,NaN,NaN
2,2021,AFC,AFC East,NE,10,7,0,0.588235,2,462,303,159,0.394118,0.480969,6.0,LostWC
3,2021,AFC,AFC East,NYJ,4,13,0,0.235294,4,310,504,-194,0.426471,0.512111,NaN,NaN
4,2021,AFC,AFC North,BAL,8,9,0,0.470588,4,387,392,-5,0.459559,0.531142,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,2011,NFC,NFC South,TB,4,12,0,0.250000,4,287,494,-207,0.437500,0.550781,NaN,NaN
348,2011,NFC,NFC West,ARI,8,8,0,0.500000,2,312,348,-36,0.390625,0.468750,NaN,NaN
349,2011,NFC,NFC West,SEA,7,9,0,0.437500,3,321,315,6,0.437500,0.511719,NaN,NaN
350,2011,NFC,NFC West,SF,13,3,0,0.812500,1,380,229,151,0.418269,0.449219,2.0,LostCC
351,2011,NFC,NFC West,LAR/STL,2,14,0,0.125000,4,193,407,-214,0.531250,0.589844,NaN,NaN

In [18]:
# Add column for superbowl champions

# create conditions for superbowl win for teams that made playoffs
superbowl_conditions = [
    (nfl_standings_df["Playoff"] == "WonSB"),
    (nfl_standings_df["Playoff"] == "LostSB"),
    (nfl_standings_df["Playoff"] == "LostCC"),
    (nfl_standings_df["Playoff"] == "LostDV"),
    (nfl_standings_df["Playoff"] == "LostWC")
]

# Create a list of the values to assign for each condition
values = ["Yes", "No", "No", "No", "No"]

# create a new column and use np.select to assign values for winning column
nfl_standings_df["Won_Superbowl"] = np.select(superbowl_conditions, values)

# replace null values with No for teams that did not make playoffs
nfl_standings_df["Won_Superbowl"].replace({"0": "No"}, inplace=True)

# display 1 year of data to ensure 1 champion
nfl_standings_df.head(32)

,Year,Conf,Division,Team,Wins,Losses,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,seed,Playoff,Won_Superbowl
0,2021,AFC,AFC East,BUF,11,6,0,0.647059,1,483,289,194,0.427807,0.472318,3.0,LostDV,No
1,2021,AFC,AFC East,MIA,9,8,0,0.529412,3,341,373,-32,0.379085,0.463668,NaN,NaN,No
2,2021,AFC,AFC East,NE,10,7,0,0.588235,2,462,303,159,0.394118,0.480969,6.0,LostWC,No
3,2021,AFC,AFC East,NYJ,4,13,0,0.235294,4,310,504,-194,0.426471,0.512111,NaN,NaN,No
4,2021,AFC,AFC North,BAL,8,9,0,0.470588,4,387,392,-5,0.459559,0.531142,NaN,NaN,No
5,2021,AFC,AFC North,CIN,10,7,0,0.588235,1,460,376,84,0.461765,0.472318,4.0,NaN,No
6,2021,AFC,AFC North,CLE,8,9,0,0.470588,3,349,371,-22,0.415441,0.513841,NaN,NaN,No
7,2021,AFC,AFC North,PIT,9,7,1,0.558824,2,343,398,-55,0.490196,0.520761,7.0,LostWC,No
8,2021,AFC,AFC South,HOU,4,13,0,0.235294,3,280,452,-172,0.397059,0.498270,NaN,NaN,No
9,2021,AFC,AFC South,IND,9,8,0,0.529412,2,451,365,86,0.431373,0.494810,NaN,NaN,No
10,2021,AFC,AFC South,JAX,3,14,0,0.176471,4,253,457,-204,0.568627,0.512111,NaN,NaN,No
11,2021,AFC,AFC South,TEN,12,5,0,0.705882,1,419,354,65,0.480392,0.472318,1.0,LostDV,No
12,2021,AFC,AFC West,DEN,7,10,0,0.411765,4,335,322,13,0.357143,0.484429,NaN,NaN,No
13,2021,AFC,AFC West,KC,12,5,0,0.705882,1,480,364,116,0.517157,0.538062,2.0,LostCC,No
14,2021,AFC,AFC West,LAC/SD,9,8,0,0.529412,3,474,459,15,0.500000,0.510381,NaN,NaN,No
15,2021,AFC,AFC West,LV/OAK,10,7,0,0.588235,2,374,439,-65,0.514706,0.510381,5.0,LostWC,No
16,2021,NFC,NFC East,DAL,12,5,0,0.705882,1,530,358,172,0.431373,0.487889,3.0,LostWC,No
17,2021,NFC,NFC East,NYG,4,13,0,0.235294,4,258,416,-158,0.485294,0.536332,NaN,NaN,No
18,2021,NFC,NFC East,PHI,9,8,0,0.529412,2,444,385,59,0.349673,0.468858,7.0,LostWC,No
19,2021,NFC,NFC East,WAS,7,10,0,0.411765,3,335,434,-99,0.420168,0.529412,NaN,NaN,No
20,2021,NFC,NFC North,CHI,6,11,0,0.352941,3,311,407,-96,0.372549,0.524221,NaN,NaN,No
21,2021,NFC,NFC North,DET,3,13,1,0.205882,4,325,467,-142,0.627451,0.527682,NaN,NaN,No
22,2021,NFC,NFC North,GB,13,4,0,0.764706,1,450,371,79,0.479638,0.479239,1.0,LostDV,No
23,2021,NFC,NFC North,MIN,8,9,0,0.470588,2,425,426,-1,0.433824,0.506920,NaN,NaN,No
24,2021,NFC,NFC South,ATL,7,10,0,0.411765,3,313,459,-146,0.315126,0.472318,NaN,NaN,No
25,2021,NFC,NFC South,CAR,5,12,0,0.294118,4,304,404,-100,0.411765,0.508651,NaN,NaN,No
26,2021,NFC,NFC South,NO,9,8,0,0.529412,2,364,335,29,0.516340,0.512111,NaN,NaN,No
27,2021,NFC,NFC South,TB,13,4,0,0.764706,1,511,353,158,0.443439,0.467128,2.0,LostDV,No
28,2021,NFC,NFC West,ARI,11,6,0,0.647059,2,449,366,83,0.491979,0.489619,5.0,LostWC,No
29,2021,NFC,NFC West,LAR/STL,12,5,0,0.705882,1,460,372,88,0.409314,0.482699,4.0,WonSB,Yes
30,2021,NFC,NFC West,SEA,7,10,0,0.411765,4,395,366,29,0.424370,0.519031,NaN,NaN,No
31,2021,NFC,NFC West,SF,10,7,0,0.588235,3,427,365,62,0.438235,0.500000,6.0,LostCC,No

In [19]:
# change playoff column to Yes or No

nfl_standings_df["Playoff"].replace({"LostSB": "Yes", "LostCC": "Yes", "LostDV": "Yes",
                                     "LostWC": "Yes", "WonSB": "Yes"}, inplace=True)

nfl_standings_df["Playoff"].fillna("No", inplace=True)

nfl_standings_df

,Year,Conf,Division,Team,Wins,Losses,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,seed,Playoff,Won_Superbowl
0,2021,AFC,AFC East,BUF,11,6,0,0.647059,1,483,289,194,0.427807,0.472318,3.0,Yes,No
1,2021,AFC,AFC East,MIA,9,8,0,0.529412,3,341,373,-32,0.379085,0.463668,NaN,No,No
2,2021,AFC,AFC East,NE,10,7,0,0.588235,2,462,303,159,0.394118,0.480969,6.0,Yes,No
3,2021,AFC,AFC East,NYJ,4,13,0,0.235294,4,310,504,-194,0.426471,0.512111,NaN,No,No
4,2021,AFC,AFC North,BAL,8,9,0,0.470588,4,387,392,-5,0.459559,0.531142,NaN,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,2011,NFC,NFC South,TB,4,12,0,0.250000,4,287,494,-207,0.437500,0.550781,NaN,No,No
348,2011,NFC,NFC West,ARI,8,8,0,0.500000,2,312,348,-36,0.390625,0.468750,NaN,No,No
349,2011,NFC,NFC West,SEA,7,9,0,0.437500,3,321,315,6,0.437500,0.511719,NaN,No,No
350,2011,NFC,NFC West,SF,13,3,0,0.812500,1,380,229,151,0.418269,0.449219,2.0,Yes,No
351,2011,NFC,NFC West,LAR/STL,2,14,0,0.125000,4,193,407,-214,0.531250,0.589844,NaN,No,No

In [20]:
# Drop seed column

nfl_standings_df = nfl_standings_df.drop(columns="seed")
nfl_standings_df

,Year,Conf,Division,Team,Wins,Losses,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won_Superbowl
0,2021,AFC,AFC East,BUF,11,6,0,0.647059,1,483,289,194,0.427807,0.472318,Yes,No
1,2021,AFC,AFC East,MIA,9,8,0,0.529412,3,341,373,-32,0.379085,0.463668,No,No
2,2021,AFC,AFC East,NE,10,7,0,0.588235,2,462,303,159,0.394118,0.480969,Yes,No
3,2021,AFC,AFC East,NYJ,4,13,0,0.235294,4,310,504,-194,0.426471,0.512111,No,No
4,2021,AFC,AFC North,BAL,8,9,0,0.470588,4,387,392,-5,0.459559,0.531142,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,2011,NFC,NFC South,TB,4,12,0,0.250000,4,287,494,-207,0.437500,0.550781,No,No
348,2011,NFC,NFC West,ARI,8,8,0,0.500000,2,312,348,-36,0.390625,0.468750,No,No
349,2011,NFC,NFC West,SEA,7,9,0,0.437500,3,321,315,6,0.437500,0.511719,No,No
350,2011,NFC,NFC West,SF,13,3,0,0.812500,1,380,229,151,0.418269,0.449219,Yes,No
351,2011,NFC,NFC West,LAR/STL,2,14,0,0.125000,4,193,407,-214,0.531250,0.589844,No,No

In [21]:
# Export team standings Dataframe to csv

nfl_standings_df_path = "../Resources/standings_df.csv"
nfl_standings_df.to_csv(nfl_standings_df_path, index=False)
nfl_standings_df

,Year,Conf,Division,Team,Wins,Losses,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won_Superbowl
0,2021,AFC,AFC East,BUF,11,6,0,0.647059,1,483,289,194,0.427807,0.472318,Yes,No
1,2021,AFC,AFC East,MIA,9,8,0,0.529412,3,341,373,-32,0.379085,0.463668,No,No
2,2021,AFC,AFC East,NE,10,7,0,0.588235,2,462,303,159,0.394118,0.480969,Yes,No
3,2021,AFC,AFC East,NYJ,4,13,0,0.235294,4,310,504,-194,0.426471,0.512111,No,No
4,2021,AFC,AFC North,BAL,8,9,0,0.470588,4,387,392,-5,0.459559,0.531142,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,2011,NFC,NFC South,TB,4,12,0,0.250000,4,287,494,-207,0.437500,0.550781,No,No
348,2011,NFC,NFC West,ARI,8,8,0,0.500000,2,312,348,-36,0.390625,0.468750,No,No
349,2011,NFC,NFC West,SEA,7,9,0,0.437500,3,321,315,6,0.437500,0.511719,No,No
350,2011,NFC,NFC West,SF,13,3,0,0.812500,1,380,229,151,0.418269,0.449219,Yes,No
351,2011,NFC,NFC West,LAR/STL,2,14,0,0.125000,4,193,407,-214,0.531250,0.589844,No,No

## Combine Datasets

In [22]:
# Merge two Dataframes

NFL_Merged_df = pd.merge(financials_df, nfl_standings_df,  how='left', 
                left_on=['Year','Team'], right_on = ['Year','Team'])
NFL_Merged_df

,Player,Year,Pos,Team,BaseSalary,SigningBonus,Cap_Hit,Salary%,Age,Cat_POS,...,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won_Superbowl
0,Mark Sanchez,2011,QB,NYJ,14225000,0,17228125,0.134,25,Offense,...,0,0.500000,2,377,363,14,0.398438,0.500000,No,No
1,Dwight Freeney,2011,OLB,IND,11420000,2500000,16420000,0.134,31,Defense,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
2,Larry Fitzgerald,2011,WR,ARI,2000000,5000000,16250000,0.133,28,Offense,...,0,0.500000,2,312,348,-36,0.390625,0.468750,No,No
3,Mario Williams,2011,DE,HOU,13800000,0,16200000,0.135,26,Defense,...,0,0.625000,1,381,278,103,0.412500,0.453125,Yes,No
4,Peyton Manning,2011,QB,IND,3400000,4000000,16000000,0.130,35,Offense,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21996,Stephen Sullivan,2021,WR,CAR,36666,0,36666,0.000,25,Offense,...,0,0.294118,4,304,404,-100,0.411765,0.508651,No,No
21997,Jalen Camp,2021,WR,HOU,36666,0,36666,0.000,23,Offense,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21998,Michael Dwumfour,2021,DT,HOU,36666,0,36666,0.000,23,Defense,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21999,Tarik Black,2021,WR,NYJ,36666,0,36666,0.000,23,Offense,...,0,0.235294,4,310,504,-194,0.426471,0.512111,No,No
22000,Connor Strachan,2021,LB,HOU,36666,0,36666,0.000,26,Defense,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No

In [23]:
# Confirm all columns have merged

NFL_Merged_df.columns

Index(['Player', 'Year', 'Pos', 'Team', 'BaseSalary', 'SigningBonus',
       'Cap_Hit', 'Salary%', 'Age', 'Cat_POS', 'Conf', 'Division', 'Wins',
       'Losses', 'Ties', 'Win%', 'Div_Rank', 'Scored', 'Allowed', 'Net', 'SOV',
       'SOS', 'Playoff', 'Won_Superbowl'],
      dtype='object')

In [24]:
# Change column order

column_names= ["Player","Age","Year","Pos","Cat_POS","Team","BaseSalary","SigningBonus","Cap_Hit","Salary%","Conf","Division","Wins","Losses","Ties","Win%","Div_Rank","Scored","Allowed","Net","SOV","SOS","Playoff","Won_Superbowl"]
NFL_Merged_df= NFL_Merged_df.reindex(columns=column_names)
NFL_Merged_df

,Player,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap_Hit,Salary%,...,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won_Superbowl
0,Mark Sanchez,25,2011,QB,Offense,NYJ,14225000,0,17228125,0.134,...,0,0.500000,2,377,363,14,0.398438,0.500000,No,No
1,Dwight Freeney,31,2011,OLB,Defense,IND,11420000,2500000,16420000,0.134,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
2,Larry Fitzgerald,28,2011,WR,Offense,ARI,2000000,5000000,16250000,0.133,...,0,0.500000,2,312,348,-36,0.390625,0.468750,No,No
3,Mario Williams,26,2011,DE,Defense,HOU,13800000,0,16200000,0.135,...,0,0.625000,1,381,278,103,0.412500,0.453125,Yes,No
4,Peyton Manning,35,2011,QB,Offense,IND,3400000,4000000,16000000,0.130,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21996,Stephen Sullivan,25,2021,WR,Offense,CAR,36666,0,36666,0.000,...,0,0.294118,4,304,404,-100,0.411765,0.508651,No,No
21997,Jalen Camp,23,2021,WR,Offense,HOU,36666,0,36666,0.000,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21998,Michael Dwumfour,23,2021,DT,Defense,HOU,36666,0,36666,0.000,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21999,Tarik Black,23,2021,WR,Offense,NYJ,36666,0,36666,0.000,...,0,0.235294,4,310,504,-194,0.426471,0.512111,No,No
22000,Connor Strachan,26,2021,LB,Defense,HOU,36666,0,36666,0.000,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No

In [25]:
# Export merged dataframe to csv

NFL_Merged_df_path = "../Resources/NFL_Merged_df.csv"
NFL_Merged_df.to_csv(NFL_Merged_df_path, index=False)
NFL_Merged_df

,Player,Age,Year,Pos,Cat_POS,Team,BaseSalary,SigningBonus,Cap_Hit,Salary%,...,Ties,Win%,Div_Rank,Scored,Allowed,Net,SOV,SOS,Playoff,Won_Superbowl
0,Mark Sanchez,25,2011,QB,Offense,NYJ,14225000,0,17228125,0.134,...,0,0.500000,2,377,363,14,0.398438,0.500000,No,No
1,Dwight Freeney,31,2011,OLB,Defense,IND,11420000,2500000,16420000,0.134,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
2,Larry Fitzgerald,28,2011,WR,Offense,ARI,2000000,5000000,16250000,0.133,...,0,0.500000,2,312,348,-36,0.390625,0.468750,No,No
3,Mario Williams,26,2011,DE,Defense,HOU,13800000,0,16200000,0.135,...,0,0.625000,1,381,278,103,0.412500,0.453125,Yes,No
4,Peyton Manning,35,2011,QB,Offense,IND,3400000,4000000,16000000,0.130,...,0,0.125000,4,243,430,-187,0.593750,0.539062,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21996,Stephen Sullivan,25,2021,WR,Offense,CAR,36666,0,36666,0.000,...,0,0.294118,4,304,404,-100,0.411765,0.508651,No,No
21997,Jalen Camp,23,2021,WR,Offense,HOU,36666,0,36666,0.000,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21998,Michael Dwumfour,23,2021,DT,Defense,HOU,36666,0,36666,0.000,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No
21999,Tarik Black,23,2021,WR,Offense,NYJ,36666,0,36666,0.000,...,0,0.235294,4,310,504,-194,0.426471,0.512111,No,No
22000,Connor Strachan,26,2021,LB,Defense,HOU,36666,0,36666,0.000,...,0,0.235294,3,280,452,-172,0.397059,0.498270,No,No

## Visualizing Data